# Generated by Django 3.0.5 on 2020-12-05 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20201128_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('US', 'United Stated of America'), ('UAE', 'United Arab Emirates'), ('Thai', 'Thailand'), ('Sing', 'Singapore'), ('France', 'France'), ('England', 'England'), ('China', 'China'), ('Thailand', 'Thailand')], default='----', max_length=100)),
                ('city', models.CharField(choices=[('Singapore', 'Singapore'), ('San Diego', 'San Diego'), ('New York', 'New York'), ('Beijing', 'Beijing'), ('Shanghai', 'Shanghai'), ('Paris', 'Paris'), ('Dubai', 'Dubai'), ('Bordeaux', 'Bordeaux'), ('London', 'London'), ('Bangkok', 'Bangkok')], default='----', max_length=100)),
                ('tour', models.CharField(choices=[('New York 3-day Adventure. Explore the City!', 'New York 3-day Adventure. Explore the City!'), ('San Diego. Explore the most popular attractions in the city!', 'San Diego. Explore the most popular attractions in the city!'), ('Discover Beijing!', 'Discover Beijing!'), ('Exploring Shanghai', 'Exploring Shanghai'), ('Walk through the Streets of Paris!', 'Walk through the Streets of Paris!'), ('Exploring Bordeaux', 'Exploring Bordeaux'), ('Discover London!', 'Discover London!'), ('Amazing 3-day Adventure at Singapore!', 'Amazing 3-day Adventure at Singapore!'), ('Experience local cultural and heritage', 'Experience local cultural and heritage')], default='----', max_length=100)),
                ('departure', models.CharField(choices=[('2021-05-10', '2021-05-10'), ('2021-01-16', '2021-01-16'), ('2021-04-05', '2021-04-05'), ('2021-07-20', '2021-07-20'), ('2021-03-05', '2021-03-05'), ('2021-04-07', '2021-04-07'), ('2021-04-08', '2021-04-08'), ('2021-03-31', '2021-03-31'), ('2021-04-04', '2021-04-04')], default='----', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
