# Generated by Django 3.0.5 on 2020-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='city',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='country',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='departure',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tour',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
