# Generated by Django 3.0.5 on 2020-12-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20201206_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='futureCompanionDescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='departure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
