# Generated by Django 3.0.5 on 2020-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20201206_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='departure',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='futureCompanionDescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tour',
            field=models.CharField(default='', max_length=100),
        ),
    ]
