# Generated by Django 3.0.5 on 2020-11-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='abcde', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('twitter_handle', models.CharField(max_length=20)),
                ('fb_handle', models.CharField(max_length=20)),
                ('insta_handle', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=13)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
