<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-11-16 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.0.5 on 2020-11-07 22:45

from django.db import migrations, models
>>>>>>> e41371ada3c229faca904d093d87e097858decb5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> e41371ada3c229faca904d093d87e097858decb5
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
=======
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='abcde', max_length=50)),
>>>>>>> e41371ada3c229faca904d093d87e097858decb5
                ('date_of_birth', models.DateField()),
                ('twitter_handle', models.CharField(max_length=20)),
                ('fb_handle', models.CharField(max_length=20)),
                ('insta_handle', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=13)),
<<<<<<< HEAD
                ('website', models.CharField(blank=True, default='', max_length=50)),
=======
>>>>>>> e41371ada3c229faca904d093d87e097858decb5
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
<<<<<<< HEAD
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('profile_pic', models.ImageField(upload_to='')),
                ('about', models.TextField()),
>>>>>>> e41371ada3c229faca904d093d87e097858decb5
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
