# Generated by Django 3.0.5 on 2020-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('attractionName', models.CharField(default='', max_length=150)),
                ('day1', models.TextField(default='')),
                ('day1_Description', models.TextField(default='')),
                ('day2', models.TextField(default='')),
                ('day2_Description', models.TextField(default='')),
                ('day3', models.TextField(default='')),
                ('day3_Description', models.TextField(default='')),
                ('guideDescription', models.TextField(default='')),
                ('departure', models.DateField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
