# Generated by Django 3.1.2 on 2020-10-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='departureDate',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='returnDate',
        ),
    ]
