# Generated by Django 3.0.5 on 2020-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='day1_condition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attraction',
            name='day2_condition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attraction',
            name='day3_condition',
            field=models.TextField(default=''),
        ),
    ]
