# Generated by Django 3.1.2 on 2020-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0002_auto_20201027_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attractionDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attractionName',
            field=models.CharField(max_length=50),
        ),
    ]
