# Generated by Django 3.1.2 on 2020-10-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0003_auto_20201027_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
