# Generated by Django 3.1.2 on 2020-10-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0005_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attractionName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
    ]
