# Generated by Django 3.1.2 on 2020-11-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0006_auto_20201028_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='departure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
